format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$cmake\
$golang\
$nodejs\
$zig\
$sudo\
$character"""

add_newline = true
command_timeout = 1000

[character] 
success_symbol = '[➜](bold green)' 
error_symbol = '[✗](bold red)'

[package]
disabled = true
